import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,writeFileSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import path from 'node:path';
import {once} from 'node:events';
import {randomUUID} from 'node:crypto';
import nodemailer from 'nodemailer';
import {SMTPServer} from 'smtp-server';
import {createApp,passwordHash} from '../server.js';
import {makeCatalog,defaults,renderContent,validateContent} from '../backend/content.js';
import {load} from 'cheerio';
const root=path.resolve(import.meta.dirname,'..');
test('catalog binds every editable text and media field without changing the structure',()=>{
 const catalog=makeCatalog(root);assert.ok(catalog.fields.length>250);
 const values=Object.fromEntries(catalog.fields.filter(f=>f.type==='text'&&!f.attr).map(f=>[f.id,`Edited ${f.id}`]));
 const html=renderContent(catalog,{values,settings:defaults});const $=load(html);
 for(const f of catalog.fields.filter(f=>f.type==='text'&&!f.attr)) assert.equal($(`[data-cms-node="${f.nodeId}"]`).contents()[f.index].data.trim(),values[f.id]);
 const source=load(catalog.template);assert.equal($('section').length,source('section').length);assert.equal($('img').length,source('img').length);
 const media=catalog.fields.find(f=>f.type==='media');assert.throws(()=>validateContent({values:{[media.id]:'javascript:alert(1)'},settings:defaults},catalog));
});
test('password, content, media, persistent enquiries and SMTP delivery',async t=>{
 const dataDir=mkdtempSync(path.join(tmpdir(),'lulu-test-'));
 const smtpMessages=[];
 const smtp=new SMTPServer({authOptional:true,disabledCommands:['STARTTLS'],onData(stream,session,callback){let raw='';stream.on('data',chunk=>raw+=chunk);stream.on('end',()=>{smtpMessages.push(raw);callback();});}});
 smtp.listen(0,'127.0.0.1');await once(smtp.server,'listening');
 const transporter=nodemailer.createTransport({host:'127.0.0.1',port:smtp.server.address().port,secure:false,ignoreTLS:true});
 writeFileSync(path.join(dataDir,'admin.json'),JSON.stringify({username:'testadmin',passwordHash:await passwordHash('test-fixture-password-123')}));
 let site=createApp({dataDir,transporter,env:{NODE_ENV:'development',APP_ORIGIN:'',SMTP_FROM:'website@example.com'}});
 let server=site.app.listen(0,'127.0.0.1');await once(server,'listening');
 let base=`http://127.0.0.1:${server.address().port}`;
 const request=(url,method='GET',body,headers={})=>fetch(base+url,{method,headers:{...(body?{'Content-Type':'application/json'}:{}),...headers},body:body?JSON.stringify(body):undefined});
 try {
  assert.equal((await request('/api/admin/content')).status,401);
  assert.equal((await request('/server.js')).status,404);assert.equal((await request('/data/site.sqlite')).status,404);
  assert.equal((await request('/api/admin/login','POST',{username:'testadmin',password:'wrong'})).status,401);
  assert.equal((await request('/api/admin/login','POST',{username:'testadmin',password:'test-fixture-password-123'},{Origin:'https://untrusted.example'})).status,403);
  const login=await request('/api/admin/login','POST',{username:'testadmin',password:'test-fixture-password-123'});assert.equal(login.status,200);
  const cookie=login.headers.get('set-cookie');assert.match(cookie,/HttpOnly/);assert.match(cookie,/SameSite=Strict/);
  const {csrf}=await login.json();const headers={Cookie:cookie.split(';')[0],'X-CSRF-Token':csrf};
  let model=await(await request('/api/admin/content','GET',null,headers)).json();
  const hero=model.fields.find(f=>f.group==='openingStory'&&f.type==='text'&&!f.attr);assert.ok(hero);
  const counter=model.fields.find(f=>f.attr==='data-count');
  model.values[hero.id]='<img src=x onerror=alert(1)> Changed hero';model.values[counter.id]='321';model.settings.headerLogoHeight=90;
  assert.equal((await request('/api/admin/content','PUT',model,{Cookie:headers.Cookie})).status,403);
  assert.equal((await request('/api/admin/content','PUT',model,headers)).status,200);
  assert.equal((await request('/api/admin/content','PUT',model,headers)).status,409);
  const page=await(await request('/')).text();assert.match(page,/&lt;img src=x onerror=alert\(1\)&gt; Changed hero/);assert.match(page,/--header-logo-height:90px/);assert.match(page,/data-count="321"/);
  const invalidUpload=new FormData();invalidUpload.append('file',new Blob(['<script>alert(1)</script>'],{type:'image/png'}),'fake.png');
  assert.equal((await fetch(base+'/api/admin/upload',{method:'POST',headers,body:invalidUpload})).status,400);
  const image=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+j2uoAAAAASUVORK5CYII=','base64');
  const upload=new FormData();upload.append('file',new Blob([image],{type:'image/png'}),'test.png');
  const uploaded=await fetch(base+'/api/admin/upload',{method:'POST',headers,body:upload});assert.equal(uploaded.status,200);const {url}=await uploaded.json();assert.equal((await request('/'+url)).status,200);
  const enquiry={requestId:randomUUID(),name:'Test Visitor',company:'Example Brand',email:'visitor@example.com',phone:'+973 12345678',message:'A retail space please.',consent:true,startedAt:Date.now()-4000};
  assert.equal((await request('/api/enquiries','POST',{...enquiry,consent:false})).status,400);
  assert.equal((await request('/api/enquiries','POST',enquiry)).status,200);
  assert.equal((await request('/api/enquiries','POST',enquiry)).status,200);
  assert.equal(smtpMessages.length,1);assert.match(smtpMessages[0],/To: leasing@lulucentre.com/);assert.match(smtpMessages[0],/Reply-To: visitor@example.com/);assert.match(smtpMessages[0],/A retail space please/);
  let inbox=await(await request('/api/admin/enquiries','GET',null,headers)).json();assert.equal(inbox.enquiries.length,1);assert.equal(inbox.enquiries[0].emailStatus,'sent');
  await new Promise(resolve=>server.close(resolve));site.close();
  site=createApp({dataDir,env:{NODE_ENV:'development',APP_ORIGIN:'',SMTP_HOST:'',SMTP_USER:'',SMTP_PASS:'',SMTP_FROM:''}});server=site.app.listen(0,'127.0.0.1');await once(server,'listening');base=`http://127.0.0.1:${server.address().port}`;
  assert.match(await(await request('/')).text(),/--header-logo-height:90px/);
  assert.equal((await request('/api/admin/content','GET',null,headers)).status,401);
  const login2=await request('/api/admin/login','POST',{username:'testadmin',password:'test-fixture-password-123'});const auth2=await login2.json();const headers2={Cookie:login2.headers.get('set-cookie').split(';')[0],'X-CSRF-Token':auth2.csrf};
  const noSMTP={...enquiry,requestId:randomUUID()};assert.equal((await request('/api/enquiries','POST',noSMTP)).status,200);
  inbox=await(await request('/api/admin/enquiries','GET',null,headers2)).json();assert.equal(inbox.enquiries.length,2);assert.equal(inbox.enquiries[0].emailStatus,'pending');
  assert.equal((await request('/api/admin/password','POST',{currentPassword:'wrong',newPassword:'new-fixture-password-456'},headers2)).status,400);
  assert.equal((await request('/api/admin/password','POST',{currentPassword:'test-fixture-password-123',newPassword:'new-fixture-password-456'},headers2)).status,200);
  assert.equal((await request('/api/admin/content','GET',null,headers2)).status,401);
 } finally {
  await new Promise(resolve=>server.close(resolve));site.close();await new Promise(resolve=>smtp.close(resolve));rmSync(dataDir,{recursive:true,force:true});
 }
});
